10-30-2023 13:58:51 | INFO | Application started
10-30-2023 13:58:58 | INFO | Application started
10-30-2023 14:02:15 | INFO | Application started
10-30-2023 14:03:33 | INFO | Application started
10-30-2023 14:05:43 | INFO | Application started
10-30-2023 14:08:51 | INFO | Application started
10-30-2023 14:08:57 | INFO | Application started
10-30-2023 14:09:10 | INFO | Application started
10-30-2023 14:09:26 | INFO | Application started
10-30-2023 14:09:26 | ERROR | Exception on /spieler [GET]
Traceback (most recent call last):
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\venv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\main.py", line 53, in player_overview_route
    uuid = minecraftApi.get_cached_uuid_from_username(user_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\utils.py", line 313, in get_cached_uuid_from_username
    uuid = db_handler.return_specific_key("cache", "UUID", "name", user_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\dataBaseOperations.py", line 91, in return_specific_key
    self.cursor.execute(query, params)
sqlite3.OperationalError: no such table: cache
10-30-2023 14:09:27 | ERROR | Exception on /spieler [GET]
Traceback (most recent call last):
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\venv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\main.py", line 53, in player_overview_route
    uuid = minecraftApi.get_cached_uuid_from_username(user_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\utils.py", line 313, in get_cached_uuid_from_username
    uuid = db_handler.return_specific_key("cache", "UUID", "name", user_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\dataBaseOperations.py", line 91, in return_specific_key
    self.cursor.execute(query, params)
sqlite3.OperationalError: no such table: cache
10-30-2023 14:09:27 | ERROR | Exception on /spieler [GET]
Traceback (most recent call last):
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\venv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\main.py", line 53, in player_overview_route
    uuid = minecraftApi.get_cached_uuid_from_username(user_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\utils.py", line 313, in get_cached_uuid_from_username
    uuid = db_handler.return_specific_key("cache", "UUID", "name", user_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\dataBaseOperations.py", line 91, in return_specific_key
    self.cursor.execute(query, params)
sqlite3.OperationalError: no such table: cache
10-30-2023 14:09:27 | ERROR | Exception on /spieler [GET]
Traceback (most recent call last):
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\venv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\main.py", line 53, in player_overview_route
    uuid = minecraftApi.get_cached_uuid_from_username(user_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\utils.py", line 313, in get_cached_uuid_from_username
    uuid = db_handler.return_specific_key("cache", "UUID", "name", user_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\dataBaseOperations.py", line 91, in return_specific_key
    self.cursor.execute(query, params)
sqlite3.OperationalError: no such table: cache
10-30-2023 14:09:27 | ERROR | Exception on /spieler [GET]
Traceback (most recent call last):
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\venv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\main.py", line 53, in player_overview_route
    uuid = minecraftApi.get_cached_uuid_from_username(user_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\utils.py", line 313, in get_cached_uuid_from_username
    uuid = db_handler.return_specific_key("cache", "UUID", "name", user_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\dataBaseOperations.py", line 91, in return_specific_key
    self.cursor.execute(query, params)
sqlite3.OperationalError: no such table: cache
10-30-2023 14:09:27 | ERROR | Exception on /spieler [GET]
Traceback (most recent call last):
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\venv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\main.py", line 53, in player_overview_route
    uuid = minecraftApi.get_cached_uuid_from_username(user_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\utils.py", line 313, in get_cached_uuid_from_username
    uuid = db_handler.return_specific_key("cache", "UUID", "name", user_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\dataBaseOperations.py", line 91, in return_specific_key
    self.cursor.execute(query, params)
sqlite3.OperationalError: no such table: cache
10-30-2023 14:10:30 | INFO | Application started
10-30-2023 14:10:30 | ERROR | Exception on /spieler [GET]
Traceback (most recent call last):
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\venv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\main.py", line 53, in player_overview_route
    uuid = minecraftApi.get_cached_uuid_from_username(user_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\utils.py", line 313, in get_cached_uuid_from_username
    uuid = db_handler.return_specific_key("cache", "UUID", "name", user_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\dataBaseOperations.py", line 91, in return_specific_key
    self.cursor.execute(query, params)
sqlite3.OperationalError: no such table: cache
10-30-2023 14:10:30 | ERROR | Exception on /spieler [GET]
Traceback (most recent call last):
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\venv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\main.py", line 53, in player_overview_route
    uuid = minecraftApi.get_cached_uuid_from_username(user_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\utils.py", line 313, in get_cached_uuid_from_username
    uuid = db_handler.return_specific_key("cache", "UUID", "name", user_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\dataBaseOperations.py", line 91, in return_specific_key
    self.cursor.execute(query, params)
sqlite3.OperationalError: no such table: cache
10-30-2023 14:10:31 | ERROR | Exception on /spieler [GET]
Traceback (most recent call last):
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\venv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\main.py", line 53, in player_overview_route
    uuid = minecraftApi.get_cached_uuid_from_username(user_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\utils.py", line 313, in get_cached_uuid_from_username
    uuid = db_handler.return_specific_key("cache", "UUID", "name", user_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\dataBaseOperations.py", line 91, in return_specific_key
    self.cursor.execute(query, params)
sqlite3.OperationalError: no such table: cache
10-30-2023 14:10:31 | ERROR | Exception on /spieler [GET]
Traceback (most recent call last):
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\venv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\main.py", line 53, in player_overview_route
    uuid = minecraftApi.get_cached_uuid_from_username(user_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\utils.py", line 313, in get_cached_uuid_from_username
    uuid = db_handler.return_specific_key("cache", "UUID", "name", user_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\dataBaseOperations.py", line 91, in return_specific_key
    self.cursor.execute(query, params)
sqlite3.OperationalError: no such table: cache
10-30-2023 14:10:31 | ERROR | Exception on /spieler [GET]
Traceback (most recent call last):
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\venv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\main.py", line 53, in player_overview_route
    uuid = minecraftApi.get_cached_uuid_from_username(user_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\utils.py", line 313, in get_cached_uuid_from_username
    uuid = db_handler.return_specific_key("cache", "UUID", "name", user_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\dataBaseOperations.py", line 91, in return_specific_key
    self.cursor.execute(query, params)
sqlite3.OperationalError: no such table: cache
10-30-2023 14:10:31 | ERROR | Exception on /spieler [GET]
Traceback (most recent call last):
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\venv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\main.py", line 53, in player_overview_route
    uuid = minecraftApi.get_cached_uuid_from_username(user_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\utils.py", line 313, in get_cached_uuid_from_username
    uuid = db_handler.return_specific_key("cache", "UUID", "name", user_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rtkal\OneDrive\Dokumente\GitHub\Full-Stack\minecraft_webserver\dataBaseOperations.py", line 91, in return_specific_key
    self.cursor.execute(query, params)
sqlite3.OperationalError: no such table: cache
10-30-2023 14:13:46 | INFO | Application started
10-30-2023 14:18:05 | INFO | Application started
10-30-2023 14:18:54 | INFO | Application started
10-30-2023 14:19:46 | INFO | Application started
10-30-2023 14:20:40 | INFO | Application started
10-30-2023 14:20:52 | INFO | Application started
10-30-2023 14:23:50 | INFO | Application started
10-30-2023 14:24:02 | INFO | Application started
10-30-2023 14:25:00 | INFO | Application started
10-30-2023 14:25:17 | INFO | Application started
10-30-2023 14:25:27 | INFO | Application started
10-30-2023 14:25:43 | INFO | Application started
10-30-2023 14:26:03 | INFO | Application started
10-30-2023 14:26:26 | INFO | Application started
10-30-2023 14:26:37 | INFO | Application started
10-30-2023 14:28:49 | INFO | Application started
10-30-2023 14:36:43 | INFO | Application started
10-30-2023 14:39:40 | INFO | Application started
10-30-2023 14:43:29 | INFO | Application started
10-30-2023 14:48:38 | INFO | Application started
10-30-2023 14:51:47 | INFO | Application started
10-30-2023 14:53:18 | INFO | Application started
10-30-2023 14:54:41 | INFO | Application started
10-30-2023 15:13:45 | INFO | Application started
10-30-2023 15:18:30 | INFO | Application started
10-30-2023 15:48:19 | INFO | Application started
10-30-2023 16:15:14 | INFO | Application started
10-30-2023 16:16:44 | INFO | Application started
10-30-2023 16:22:32 | INFO | Application started
10-30-2023 16:26:01 | INFO | Application started
10-30-2023 16:27:03 | INFO | Application started
10-30-2023 16:33:07 | INFO | Application started
10-30-2023 16:37:50 | INFO | Application started
10-30-2023 16:41:34 | INFO | Application started
10-30-2023 16:45:01 | INFO | Application started
10-30-2023 16:45:35 | INFO | Application started
10-30-2023 16:46:12 | INFO | Application started
10-30-2023 16:49:31 | INFO | Application started
10-30-2023 17:05:21 | INFO | Application started
10-30-2023 17:06:07 | INFO | Application started
